const myIslamBaseUrl = "https://myislam.org/99-names-of-allah";

const myIslamSlugs = [
  "ar-rahman",
  "ar-raheem",
  "al-malik",
  "al-quddus",
  "as-salam",
  "al-mumin",
  "al-muhaymin",
  "al-aziz",
  "al-jabbar",
  "al-mutakabbir",
  "al-khaliq",
  "al-bari",
  "al-musawwir",
  "al-ghaffar",
  "al-qahhar",
  "al-wahhab",
  "ar-razzaq",
  "al-fattah",
  "al-alim",
  "al-qabid",
  "al-basit",
  "al-khafid",
  "ar-rafi",
  "al-muizz",
  "al-muzil",
  "as-sami",
  "al-baseer",
  "al-hakam",
  "al-adl",
  "al-lateef",
  "al-khabir",
  "al-haleem",
  "al-azeem",
  "al-ghafoor",
  "ash-shakur",
  "al-aliyy",
  "al-kabeer",
  "al-hafiz",
  "al-muqeet",
  "al-haseeb",
  "al-jaleel",
  "al-karim",
  "ar-raqib",
  "al-mujeeb",
  "al-wasi",
  "al-hakeem",
  "al-wadud",
  "al-majeed",
  "al-baith",
  "ash-shaheed",
  "al-haqq",
  "al-wakeel",
  "al-qawiyy",
  "al-matin",
  "al-waliy",
  "al-hameed",
  "al-muhsi",
  "al-mubdi",
  "al-muid",
  "al-muhyi",
  "al-mumeet",
  "al-hayy",
  "al-qayyum",
  "al-wajid",
  "al-maajid",
  "al-wahid",
  "al-ahad",
  "as-samad",
  "al-qadir",
  "al-muqtadir",
  "al-muqaddim",
  "al-muakhkhir",
  "al-awwal",
  "al-akhir",
  "az-zaahir",
  "al-baatin",
  "al-wali",
  "al-mutaali",
  "al-barr",
  "at-tawwab",
  "al-muntaqim",
  "al-afuw",
  "ar-rauf",
  "malikul-mulk",
  "dhul-jalaali-wal-ikram",
  "al-muqsit",
  "al-jami",
  "al-ghaniy",
  "al-mughni",
  "al-mani",
  "ad-darr",
  "an-naafi",
  "an-noor",
  "al-hadi",
  "al-badi",
  "al-baaqi",
  "al-warith",
  "ar-rasheed",
  "as-sabur",
];

const sourceCatalog = {
  britannica: {
    label: "Britannica",
    url: "https://www.britannica.com/topic/99-names-of-God",
  },
  islamClear: {
    label: "IslamClear",
    url: "https://islamclear.com/names-of-allah/",
  },
  myIslam: {
    label: "MyIslam",
    url: myIslamBaseUrl,
  },
  names99: {
    label: "99NamesOfAllah.name",
    url: "https://99namesofallah.name/",
  },
};

function getMyIslamDetailSource(id) {
  return {
    ...sourceCatalog.myIslam,
    url: `${myIslamBaseUrl}/${myIslamSlugs[id - 1]}/`,
  };
}

export function createNameDetail(name, explanation) {
  const rootLine = name.root
    ? `Its Arabic root is ${name.root}. ${name.rootNote}`
    : `${name.transliteration} is understood through its established meaning: ${name.meaning}.`;

  return {
    title: `${name.transliteration}: ${name.meaning}`,
    summary: explanation,
    paragraphs: [
      `${name.transliteration} (${name.arabic}) teaches that Allah is ${name.meaning.toLowerCase()}. This Name is not only a label; it points to a perfect attribute of Allah, understood in a way that befits His majesty and is unlike created qualities.`,
      rootLine,
      `Reflecting on ${name.transliteration} should move the heart from memorization into worship. A believer can call upon Allah by this Name, notice its meaning in daily life, and let it shape trust, humility, gratitude, patience, and reliance on Him.`,
    ],
    practice:
      "Read the Arabic Name slowly, repeat the transliteration, then make a short du'a connected to the meaning before moving on.",
    sources: [
      getMyIslamDetailSource(name.id),
      sourceCatalog.britannica,
      sourceCatalog.islamClear,
      sourceCatalog.names99,
    ],
  };
}
