export const nameExplanations = [
  "Allah's mercy reaches every creature with goodness, care, and compassion.",
  "Allah shows special, continuous mercy to those who turn toward Him.",
  "Allah owns all dominion and rules with complete authority.",
  "Allah is perfectly holy and free from every defect or imperfection.",
  "Allah is free from all flaws, and true peace comes from Him.",
  "Allah grants safety, faith, and reassurance to those who trust Him.",
  "Allah watches over creation and preserves what He wills.",
  "Allah is mighty, undefeated, and cannot be overcome.",
  "Allah's will prevails, and He restores what is broken.",
  "Allah is exalted above creation and unlike anything He created.",
  "Allah brings things from non-existence into existence.",
  "Allah originates creation and gives each being its distinct form.",
  "Allah shapes creation in beautiful and varied forms.",
  "Allah forgives again and again, covering the faults of His servants.",
  "Allah has perfect power and complete dominance over all things.",
  "Allah gives generously without needing repayment or benefit.",
  "Allah provides and sustains every living being.",
  "Allah opens closed paths, relieves hardship, and judges with wisdom.",
  "Nothing is hidden from Allah's complete and eternal knowledge.",
  "Allah withholds by wisdom and restricts what He wills.",
  "Allah expands provision, relief, and opportunity by His generosity.",
  "Allah lowers whom He wills according to His wisdom and justice.",
  "Allah raises whom He wills in rank, honor, and nearness.",
  "Allah grants honor, and no one can degrade whom He honors.",
  "Allah humbles whom He wills, and no one can honor against His will.",
  "Allah hears every sound, spoken or hidden, without limitation.",
  "Allah sees every visible and hidden thing with perfect sight.",
  "Allah judges with absolute authority, and His judgment is truth.",
  "Allah is perfectly just and never wrongs anyone.",
  "Allah is subtle, gentle, and kind in ways people may not notice.",
  "Allah knows the inner reality and hidden truth of all things.",
  "Allah is forbearing and may delay punishment while opening the door to forgiveness.",
  "Allah is magnificent, mighty, and worthy of every form of exaltation.",
  "Allah forgives abundantly and repeatedly.",
  "Allah rewards sincere obedience with generosity far beyond the deed.",
  "Allah is the Most High, far above every created limitation.",
  "Allah is greater than everything in status, power, and majesty.",
  "Allah preserves and protects whatever and whoever He wills.",
  "Allah maintains, nourishes, and has power over all needs.",
  "Allah reckons all deeds and is sufficient for His servants.",
  "Allah possesses perfect majesty, glory, and greatness.",
  "Allah is generous, noble, and bountiful in giving.",
  "Allah watches over everything; nothing escapes Him.",
  "Allah answers those who call upon Him and rescues those in need.",
  "Allah is vast in knowledge, mercy, power, and generosity.",
  "Allah places everything with perfect wisdom and right judgment.",
  "Allah loves and shows affection to those who seek Him.",
  "Allah is glorious in power, rank, generosity, and kindness.",
  "Allah resurrects and brings creation back to life after death.",
  "Allah witnesses all things, and nothing is absent from Him.",
  "Allah is the absolute truth and the One whose existence is real and necessary.",
  "Allah is the trustee relied upon for every affair.",
  "Allah has complete strength and perfect power.",
  "Allah's power is firm, constant, and never weakened.",
  "Allah protects, supports, and cares for those who turn to Him.",
  "Allah alone deserves all praise.",
  "Allah knows and counts every detail without error.",
  "Allah begins creation from nothing.",
  "Allah restores creation and brings it back after death.",
  "Allah gives life and restores living beings.",
  "Allah creates death and causes life to end at its appointed time.",
  "Allah is eternally living with a life unlike created life.",
  "Allah is self-subsisting, and all creation depends on Him.",
  "Allah finds, perceives, and is never in need.",
  "Allah is noble, glorious, and perfect in honor.",
  "Allah is one, unique, and without any partner.",
  "Allah is absolutely one and incomparable.",
  "Allah is the eternal refuge whom creation turns to in need.",
  "Allah has complete ability over all things.",
  "Allah's power is perfect, dominant, and unrestricted.",
  "Allah advances what He wills and places matters in their proper order.",
  "Allah delays what He wills by wisdom and perfect knowledge.",
  "Allah is the First, whose existence has no beginning.",
  "Allah is the Last, whose existence has no end.",
  "Allah is manifest through His signs and above all things.",
  "Allah knows what is hidden, inward, and unseen.",
  "Allah governs, owns, and manages all affairs.",
  "Allah is exalted above every attribute of creation.",
  "Allah is the source of goodness and is kind to His creation.",
  "Allah accepts repentance and repeatedly turns His servants back to mercy.",
  "Allah can punish wrongdoing with perfect justice.",
  "Allah pardons, erases sins, and overlooks faults.",
  "Allah is tenderly kind and deeply compassionate.",
  "Allah controls dominion and grants authority as He wills.",
  "Allah possesses majesty, honor, and boundless generosity.",
  "Allah is equitable and perfectly just in His judgment.",
  "Allah gathers creation together for the Day of Judgment.",
  "Allah is free of need, while all creation depends on Him.",
  "Allah enriches and fulfills needs by His bounty.",
  "Allah withholds and prevents according to wisdom.",
  "Allah can allow hardship, correction, and harm by His decree.",
  "Allah creates benefit and grants what is useful.",
  "Allah is the Light who guides hearts and creation.",
  "Allah guides to the straight path.",
  "Allah originates creation in an unmatched and unprecedented way.",
  "Allah remains forever and never passes away.",
  "Allah is the inheritor; all creation returns to Him.",
  "Allah guides with perfect direction and uprightness.",
  "Allah is patient and does not hasten punishment for sinners.",
];
